var timers = require('./timers.js');
var exec = require('child_process').exec;
var Log = require('./logger.js');

var tagPNG = function(filename) {
    return new Promise(function(resolve, reject) {
        timers.start('tag-png');
        var tagchild;
        tagchild = exec('mogrify -comment "Generated by DrumGen for your practicing enjoyment" ' + filename + '.png', function(err, stdout, stderr) {
            timers.end('tag-png');
            Log.debug('stdout: ' + stdout);
            Log.debug('stderr: ' + stderr);
            if (err) {
                Log.error(err);
                reject();
            }
            resolve();
        });
    });
};

var tagOGG = function(filename) {
    return new Promise(function(resolve, reject) {
        var tagchild;
        timers.start('tag-ogg');
        tagchild = exec('lltag --yes --ogg -a "DrumGen" -d `date` -t "' + filename + '" -c "Generated for your practicing enjoyment" ' + filename + '.ogg', function(err, stdout, stderr) {
            timers.end('tag-ogg');
            Log.debug('stdout: ' + stdout);
            Log.debug('stderr: ' + stderr);
            if (err) {
                Log.error(err);
                reject();
            }
            resolve();
        });
    });
};

module.exports = {
    tagPNG: tagPNG,
    tagOGG: tagOGG
}
