/* global module */
/* jshint strict:false */

var timers = require('./timers.js');
var exec = require('child_process').exec;
var Log = require('./logger.js');
var png = require('png-metadata');
var fs = require('fs');


var tagPNG_old = function(filename) {
    return new Promise(function(resolve, reject) {
        timers.start('tag-png');
        var tagchild;
        tagchild = exec('mogrify -comment "Generated by DrumGen for your practicing enjoyment" ' + filename + '.png', function(err, stdout, stderr) {
            timers.end('tag-png');
            Log.debug('stdout: ' + stdout);
            Log.debug('stderr: ' + stderr);
            if (err) {
                Log.error(err);
                reject();
            }
            resolve();
        });
    });
};

var tagPNG = function(filename) {
    return new Promise(function(resolve, reject) {
        timers.start('tag-png');

        try {
            // load from file
            var s = png.readFileSync(filename + '.png');
            // split
            var list = png.splitChunk(s);
            // append
            var iend = list.pop(); // remove IEND
            var newchunk = png.createChunk("tEXt", "Comment\0Generated by DrumGen for your practicing enjoyment");
            list.push(newchunk);
            list.push(iend);
            // join
            var newpng = png.joinChunk(list);
            // save to file
            fs.writeFileSync(filename + '.png', newpng, 'binary');
            timers.end('tag-png');
            resolve();
        } catch (e) {
            timers.end('tag-png');
            reject(e);
        }

    });
};

var tagOGG = function(filename) {
    return new Promise(function(resolve, reject) {
        var tagchild;
        timers.start('tag-ogg');
        //tagchild = exec('lltag --yes --ogg -a "DrumGen" -d `date` -t "' + filename + '" -c "Generated for your practicing enjoyment" ' + filename + '.ogg', function(err, stdout, stderr) {
        tagchild = exec('vorbiscomment -a -t "AUTHOR=DrumGen" -t "DATE=`date`" -t "NAME=' + filename + '" -t "COMMENT=Generated for your practicing enjoyment" ' + filename + '.ogg', function(err, stdout, stderr) {
            timers.end('tag-ogg');
            Log.debug('stdout: ' + stdout);
            Log.debug('stderr: ' + stderr);
            if (err) {
                Log.error(err);
                reject();
            }
            resolve();
        });
    });
};

module.exports = {
    tagPNG: tagPNG,
    tagOGG: tagOGG
};
